import aiohttp
import asyncio
import re
import time
import os
from typing import List, Tuple

async def extract_channel_name(url: str) -> str:
    """URL'den kanal adını çıkart"""
    patterns = [
        r'/([^/]+)\.(?:m3u8|mp4|ts)',
        r'/([^/]+?)(?:\?|$)',
        r'/([^/]+)/index',
        r'/([^/]+)\.m3u8',
    ]
    
    for pattern in patterns:
        match = re.search(pattern, url)
        if match:
            name = match.group(1)
            # Temizlik
            name = name.replace('_', ' ').replace('-', ' ')
            name = re.sub(r'\d+[kKpP]', '', name)
            name = re.sub(r'\.(m3u8|mp4|ts)$', '', name)
            return name.title().strip()
    return "Bilinmeyen Kanal"

async def test_stream_url(session: aiohttp.ClientSession, url: str, channel_name: str, semaphore: asyncio.Semaphore) -> Tuple[str, str, bool]:
    """Tek bir URL'yi test et - asenkron"""
    async with semaphore:
        try:
            # Timeout ayarları
            timeout = aiohttp.ClientTimeout(total=5, connect=3)
            
            # Önce HEAD isteği dene
            try:
                async with session.head(url, timeout=timeout, allow_redirects=True) as response:
                    if response.status == 200:
                        return (url, channel_name, True)
            except:
                pass
            
            # HEAD çalışmazsa GET ile dene (sadece header)
            try:
                async with session.get(url, timeout=timeout) as response:
                    if response.status == 200:
                        return (url, channel_name, True)
            except:
                pass
                
        except asyncio.TimeoutError:
            pass
        except Exception:
            pass
        
        return (url, channel_name, False)

def read_channels() -> List[str]:
    """channels.txt dosyasını oku"""
    try:
        with open('channels.txt', 'r', encoding='utf-8') as f:
            channels = []
            for line in f:
                line = line.strip()
                # Yorum satırlarını ve boş satırları atla
                if line and not line.startswith('#'):
                    channels.append(line)
            return channels
    except FileNotFoundError:
        print("❌ channels.txt dosyası bulunamadı!")
        return []
    except Exception as e:
        print(f"❌ Hata: {e}")
        return []

async def batch_test_urls_async(channels: List[str]) -> List[str]:
    """Tüm URL'leri paralel olarak test et"""
    working_streams = []
    
    # Bağlantı limitleri (GitHub Actions için optimize)
    connector = aiohttp.TCPConnector(
        limit=50,  # Max 50 paralel bağlantı
        limit_per_host=20,  # Aynı host'a max 20 bağlantı
        ttl_dns_cache=300,  # DNS cache 5 dakika
        enable_cleanup_closed=True
    )
    
    # Semaphore ile eşzamanlı istek limiti
    max_concurrent = int(os.getenv('MAX_WORKERS', 30))
    semaphore = asyncio.Semaphore(max_concurrent)
    
    async with aiohttp.ClientSession(connector=connector) as session:
        tasks = []
        
        for channel in channels:
            # Kanal formatı: "Kanal Adı::URL" veya sadece "URL"
            if '::' in channel:
                name, url = channel.split('::', 1)
                tasks.append(test_stream_url(session, url.strip(), name.strip(), semaphore))
            else:
                url = channel
                name = await extract_channel_name(url)
                tasks.append(test_stream_url(session, url, name, semaphore))
        
        print(f"🚀 {len(tasks)} kanal test ediliyecek ({max_concurrent} paralel)...")
        
        # Tüm testleri bekle
        results = await asyncio.gather(*tasks, return_exceptions=True)
        
        # Sonuçları işle
        for result in results:
            if isinstance(result, tuple) and result[2]:  # Çalışan kanal
                url, name, _ = result
                working_streams.append(f"{name},{url}")
    
    return working_streams

def create_m3u8_file(working_streams: List[str]) -> None:
    """M3U8 dosyası oluştur"""
    content = "#EXTM3U\n"
    content += "# Playlist generated by Async M3U Creator\n"
    content += f"# Total channels: {len(working_streams)}\n"
    content += f"# Generated: {time.strftime('%Y-%m-%d %H:%M:%S')}\n\n"
    
    for stream in working_streams:
        try:
            name, url = stream.split(',', 1)
            # M3U8 formatı
            content += f'#EXTINF:-1 tvg-logo="" group-title="TV",{name}\n'
            content += f'{url}\n'
        except Exception as e:
            print(f"⚠️ Hata: {e}")
            continue
    
    # Dosyaya yaz
    try:
        with open('tv247.m3u', 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"✅ tv247.m3u dosyası oluşturuldu ({len(working_streams)} kanal)")
    except Exception as e:
        print(f"❌ Dosya yazma hatası: {e}")

async def main_async():
    """Ana asenkron fonksiyon"""
    print("🎬 Async M3U Playlist Oluşturucu Başlıyor...")
    print("=" * 50)
    
    # Kanalları oku
    channels = read_channels()
    if not channels:
        print("❌ Kanal bulunamadı! Lütfen channels.txt dosyasını kontrol edin.")
        return
    
    print(f"📺 Toplam {len(channels)} kanal bulundu")
    
    # Başlangıç zamanı
    start_time = time.time()
    
    # URL'leri test et
    working_streams = await batch_test_urls_async(channels)
    
    # Geçen süre
    elapsed = time.time() - start_time
    
    # Sonuçları göster
    print("=" * 50)
    print(f"✨ Tarama tamamlandı!")
    print(f"⏱️  Süre: {elapsed:.2f} saniye")
    print(f"✅ Çalışan kanal: {len(working_streams)}/{len(channels)}")
    print(f"❌ Çalışmayan: {len(channels) - len(working_streams)}")
    
    # M3U8 oluştur
    if working_streams:
        create_m3u8_file(working_streams)
        print("🎉 İşlem başarıyla tamamlandı!")
    else:
        print("⚠️ Hiç çalışan kanal bulunamadı!")

def main():
    """Ana fonksiyon"""
    try:
        asyncio.run(main_async())
    except KeyboardInterrupt:
        print("\n⚠️ İşlem kullanıcı tarafından durduruldu")
    except Exception as e:
        print(f"❌ Beklenmeyen hata: {e}")

if __name__ == "__main__":
    main()
